### ISSUE TITLE
Angular Endpoint

### ISSUE THREAD

**Issue by RafaelZasas** [bubthegreat/angular-fastapi#7]
Where is the HTTP Client section where you make a get request to Fast Api ?

**Comment by bubthegreat** [comment]
This cookiecutter example looks to be out of date - check out https://github.com/bubthegreat/cookiecutter-angular-fastapi - you'll find it there.  I'll update this repo shortly - I was in the middle of adding auth and switched to GINO for the ORM because it supports asyncio and migrations through alembic.

**Comment by RafaelZasas** [comment]
Thank you!  I’m still struggling to find a way to make secure HTTP requests to my FastAPI. It says its being blocked because the request was made from a secure site.Any advice? Rafael ZasasUniversity of Redlands 21’B.S Computer Science Major & Math/Physics MinorPhone: +1 310 600 2053 LinkedIn: www.linkedin.com/in/rafael-zasas/Git Hub: https://github.com/RafaelZasasWebsite: http://rafaelzasas.com/ From: Micheal TaylorSent: Tuesday, August 4, 2020 8:52 PMTo: bubthegreat/angular-fastapiCc: Rafael Zasas; AuthorSubject: Re: [bubthegreat/angular-fastapi] Angular Endpoint (#7) This cookiecutter example looks to be out of date - check out https://github.com/bubthegreat/cookiecutter-angular-fastapi - you'll find it there. I'll update this repo shortly - I was in the middle of adding auth and switched to GINO for the ORM because it supports asyncio and migrations through alembic.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bubthegreat** [comment]
Sorry, I lead you wrong- this is the actual link - https://gitlab.com/bubthegreat/cookiecutter-angular-fastapi  - I maintain the project in gitlab now - but the github link should work for the time being.  I'm trying to find time to update a full example with GINO for the database at this point

**Comment by bubthegreat** [comment]
@RafaelZasas - I actually finished a better implementation of the backend that I'll be integrating into this that uses asyncio and has an async ORM: https://gitlab.com/bubthegreat/cookiecutter-gino-fastapi.git

Just finished getting some initial user permissions worked out and token auth functioning - this work was the major blocker for adding a user management interface and some basic CRUD interfaces.
